### ISSUE TITLE
编译crdroid时遇到sepolicy文件冲突

### ISSUE THREAD

**Issue by dsfssdfd** [Redmi-K50/device_xiaomi_mt6895-common#1]
FAILED: build out/target/product/rubens/obj/ETC/sepolicy.recovery_intermediates/sepolicy
Outputs: out/target/product/rubens/obj/ETC/sepolicy.recovery_intermediates/sepolicy
Error: exited with code: 1
Command: /bin/bash -c "(ASAN_OPTIONS=detect_leaks=0 out/host/linux-x86/bin/checkpolicy -M -c 		30 -o out/target/product/rubens/obj/ETC/sepolicy.recovery_intermediates/sepolicy.tmp out/target/product/rubens/obj/ETC/sepolicy.recovery_intermediates/sepolicy.recovery.conf ) && (out/host/linux-x86/bin/sepolicy-analyze out/target/product/rubens/obj/ETC/sepolicy.recovery_intermediates/sepolicy.tmp permissive > out/target/product/rubens/obj/ETC/sepolicy.recovery_intermediates/sepolicy.permissivedomains ) && (sed -i '/backuptool/d' out/target/product/rubens/obj/ETC/sepolicy.recovery_intermediates/sepolicy.permissivedomains ) && (sed -i '/recovery/d' out/target/product/rubens/obj/ETC/sepolicy.recovery_intermediates/sepolicy.permissivedomains ) && (if [ \"userdebug\" = \"user\" -a -s out/target/product/rubens/obj/ETC/sepolicy.recovery_intermediates/sepolicy.permissivedomains ]; then 		echo \"==========\" 1>&2; 		echo \"ERROR: permissive domains not allowed in user builds\" 1>&2; 		echo \"List of invalid domains:\" 1>&2; 		cat out/target/product/rubens/obj/ETC/sepolicy.recovery_intermediates/sepolicy.permissivedomains 1>&2; 		exit 1; 		fi ) && (mv out/target/product/rubens/obj/ETC/sepolicy.recovery_intermediates/sepolicy.tmp out/target/product/rubens/obj/ETC/sepolicy.recovery_intermediates/sepolicy )"
Output:
device/xiaomi/mt6895-common/sepolicy/vendor/ccci_mdinit.te:2:ERROR 'Duplicate declaration of type' at token ';' on line 121363:
#line 1 "device/xiaomi/mt6895-common/sepolicy/vendor/ccci_mdinit.te"
type data_vendor_de_md_file, file_type, data_file_type;
checkpolicy:  error(s) encountered while parsing configuration
请教下大佬应该怎么解决，谢谢

**Comment by YuKongA** [comment]
自己解决冲突

**Comment by dsfssdfd** [comment]
好谢谢
